steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']
    dir: 'functions'

  # Deploy Firebase Functions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install Firebase CLI
        npm install -g firebase-tools
        
        # Authenticate using service account
        gcloud auth activate-service-account --key-file=/workspace/firebase-service-account-key.json
        
        # Set the project
        firebase use bytefit-f3be8
        
        # Deploy functions
        firebase deploy --only functions
    dir: '.'
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/firebase-service-account-key.json'

# Use custom service account for Cloud Build
serviceAccount: 'projects/bytefit-f3be8/serviceAccounts/firebase-cloudbuild@bytefit-f3be8.iam.gserviceaccount.com'

# Set timeout
timeout: '1200s'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'